// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomPosition() {
  return window['go']['main']['App']['GetRandomPosition']();
}

export function GetScreenSize() {
  return window['go']['main']['App']['GetScreenSize']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MoveWindow(arg1, arg2) {
  return window['go']['main']['App']['MoveWindow'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
