// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomPosition():Promise<Record<string, number>>;

export function GetScreenSize():Promise<Record<string, number>>;

export function Greet(arg1:string):Promise<string>;

export function MoveWindow(arg1:number,arg2:number):Promise<void>;

export function Quit():Promise<void>;
